<p>This test verifies that an exception throw in host code after an intial script
execution is not reported to the console if it is caught at a higher level.
</p>

<p>If the console does not say 'FAIL', the test has passed.</p>
<script>
<!--
(function () {
    if (window.layoutTestController)
        layoutTestController.dumpAsText();

    try {
        document.write("<script></script>");
        document.write("<script>throw 'FAIL';</script>");
    } catch(e) {
    }
})();
-->
</script>
